### ISSUE TITLE
Restore previous table state also as MATERIALIZED VIEWs

### ISSUE THREAD

**Issue by FxKu** [pgMemento/pgMemento#25]
Had it in the beginning. Dropped it then. But should not be hard to bring it back. Question is what literal shall be used for `target_table_type` parameter?

`MATERIALIZED VIEW` - propably good to integrated in scripts
`MVIEW` or `MATVIEW` - shorter and faster to write, when executed manually

Maybe both forms should be supported.

**Comment by dnsl48** [comment]
> MATERIALIZED VIEW - propably good to integrated in scripts

It feels more consistent and corresponding to the SQL standards

> MVIEW or MATVIEW - shorter and faster to write, when executed manually

Does not feel like this operation is so often executed manually that it's worth supporting those forms for the time economy sake :)

**Comment by FxKu** [comment]
Yes, right. Will probably go for `MATERIALIZED VIEW`.

**Comment by FxKu** [comment]
Solved with 254ae0d
