### ISSUE TITLE
Logging multiple table events of the same type

### ISSUE THREAD

**Issue by FxKu** [pgMemento/pgMemento#26]
Idea: Add a timestamp column to `table_event_log` and feed it with `statement_timestamp()`. This way multiple events of the same type can be logged per transaction. Important question is: Can INSERTs into `row_log` be referenced correctly and fast enough (`statememt_timestamp` needs to be the same in BEFORE and AFTER phase!). Previous attemps to use transaction variables also for table events decreased the logging performance. So, this might not be an option then.

A change in the event logging would also affect the code in DDL_LOG, REVERT and SETUP where logging only one event per transaction is used as a feature (by calling `log_table_event` manually).

**Comment by dnsl48** [comment]
> Previous attemps to use transaction variables also for table events decreased the logging performance

Just out of interest: how did you measure the performance then?

**Comment by FxKu** [comment]
Using pgbench and TPS count. This is what I used last time and it made me reduce my extensive use of transaction variables that I wanted to introduce in `v0.6`.

**Comment by FxKu** [comment]
Now that's interesting:
```
DO
$$
BEGIN
  FOR i IN 1..2 LOOP
    RAISE NOTICE 'tx time: %', transaction_timestamp();
    RAISE NOTICE 'stmt time: %', statement_timestamp();
    COMMIT;
    PERFORM pg_sleep(0.1);
  END LOOP;
END;
$$
LANGUAGE plpgsql;
```

`statement_timestamp` remains constant while `transaction_timestamp` is updated ...
