### ISSUE TITLE
RFC | Make audit_id less invasive

### ISSUE THREAD

**Issue by dnsl48** [pgMemento/pgMemento#27]
# Description

`pgMemento v0.6` implements row level tracking by [adding a field named `audit_id`](https://github.com/pgMemento/pgMemento/blob/v0.6/src/SETUP.sql#L556) to tables.

This RFC proposes to improve the `audit_id` implementation to make it less invasive.

# Problem statement

`audit_id` is a quite common name for a table column, which may conflict with native table data structure.
Currently, pgMemento does not provide any means to configure or change that behaviour.

Customization of the column name might seem to be too complicated and even over-engineering. However, it could be done some time in the future without introducing breaking changes to the module.

On the other hand, `picking a more unique name for the column` introduces somewhat breaking changes, whereas it is quite easy to implement without much complexity and effort.

# Proposal

I suggest we change the `audit_id` column name to something quite unique so that it reduces chances of conflicting with native data column names. Ideally it should contain the name of the extension as prefix.

## Possible options

 - `Option A` is `"pgmemento audit_id"`. Use `space` to separate prefix and column name
 - `Option B` is `"pgmemento__audit_id"`. Use `two underscores` to separate prefix and column name

**Comment by dnsl48** [comment]
My personal preference would be to use `space` as it's the most unique option in my opinion, and it is really hard to accidentally use it without knowing exactly what you are doing.

**Comment by FxKu** [comment]
Hehe, I was waiting for someone to point at this. `audit_id` is a too generic name, indeed. Not sure about the space. I would never use spaces in SQL identifiers myself. So it would be weird for me to do it here, now. Why not `pgmemento_audit_id` with one underscore? Who would really use this? Or maybe `pgmemento__audit__id`? Like the idea of putting the extension name in the column title. This way, everybody is able to figure out, why this column might be there.

In the past, there have also been users, who did not like the idea of having an extra surrogate key. But, I did not have any better idea which is as easy as adding a tracer in each table and a reference in the `row_log`.

**Comment by dnsl48** [comment]
> I would never use spaces in SQL identifiers myself

Haha, that's exactly why I think that's the most unique and less invasive option. Nobody uses spaces :smile: 

> Or maybe pgmemento__audit__id? 

Yeah, that's the second option I mentioned. I don't see a reason to have double underscore for `audit__id` too, but for the prefix (or we could name it a namespace) feels more appropriate, so `pgmemento__audit_id` should be good enough I think.

> Why not `pgmemento_audit_id` with one underscore?

That feels too standard. If someone ever decides to keep pgmemento audit id in their tables for whatever reasons, that would be the name they pick, and in that case we would interfere.

**Comment by dnsl48** [comment]
I've been thinking about this a bit, and _I think_ that that 90% of the data tables out there would be normalized and have their own PK.
If we consider moving from using OID to using schema and table names, then we potentially could also store the `audit_id` column name in the same place. Potentially that could give us flexibility to use the original tables PK fields instead of adding `audit_id` field to every table and only add it where the table does not have a PK.

This means we might have a 3rd option here. When registering a table as audited with pgMemento, we could pick an existing PK field as audit_id, or if there's none, we could fall back to the original behaviour and generate `audit_id`.
The only issue I can see with that approach is different PK fields might have different types. E.g. INT, BIGINT and even UUID.

**Comment by FxKu** [comment]
What about junction tables where the PK comprises of multiple columns? I've added an extra surrogate key everywhere just to make my life easier. Plus, I like the uniqueness of the `audit_id` across tables (or even schemas). Could become interesting with branching.

**Comment by dnsl48** [comment]
> What about junction tables where the PK comprises of multiple columns?
those still may be handled through falling back to a custom field just like it is right now.

> I like the uniqueness of the audit_id across tables (or even schemas)
yes, I love it too :) however, it would be awesome to have it unique across databases as well. I'm considering a microservice scenario, where a single table might be migrated to another microservice, ideally we would want to move its audit data too. If we had it decoupled from current database sequence, that could be achievable.
One way to do that is to use uuid instead of an integer sequence. Another way is to toss in schema and table name and make it a composite of three, rather than relying on its own uniqueness.

**Comment by FxKu** [comment]
I think that's another topic ;)
The audit trail is not only the `audit_id` but also the logged transaction and table event metadata. This design makes it very complicated, if not impossible to have such a pluggable history. It would work when using a shadow table pattern, where you have an audit trail for each table, I guess.

**Comment by dnsl48** [comment]
Agree, though somewhat related to audit_id :)
Just giving you the context of my thoughts, so it's more clear why I come up with some crazy stuff like that :joy: 
Yeah, I guess I'll need to get more familiar with the whole metadata structure before I can discuss it in more depth.

**Comment by dnsl48** [comment]
Yeah, thought about it too. I also tend to have UUIDs everywhere.
However, pgMemento does keep audit_id as integers at the moment, and I'm not sure UUID is more common approach to PKs rather than serials. I think we have 2 different problems here.
 - should `audit_id` be an integer or UUID (in the  second case pgMemento will require pgcrypto as a dependency and occupy more disk space)
 - should `audit_id` be a customisable field for every table, or to be maintained in a generic way by pgMemento

**Comment by FxKu** [comment]
As @dnsl48 mentioned, pgMemento relies on integers for tracing different versions in the audit trail. I could think of relaxing this setup by allowing users to define the audit column themselves (if it's an `int`), or rely on the PK. When it's not an `int` or the PK consists of multiple columns I could switch to the current behavior. There could be an extra column in the `audit_table_log` where this info is stored.
Using UUIDs (or other datatypes) can only work, if all tables follow this style (and if not UUID would be the default then).

All possible, I guess. It's not, that I don't like these ideas - although I don't need it for my use cases. It's just the lack of free time on my side that hinders me to implement it. So, feel free to create PRs :)

**Comment by nextstopsun** [comment]
What if a column type could be set system-wise (i.e. during installation), and column names could be custom set for each table in `audit_table_log`? 
This doesn't break current logic while adding a bit of flexibility.

**Comment by FxKu** [comment]
The name of the audit_id column is now configurable. It's data type is not, though.
