### ISSUE TITLE
TEST.sql fails in clean database

### ISSUE THREAD

**Issue by raiviskrumins** [pgMemento/pgMemento#28]
TEST.sql fails with
```
TEST 1: pgMemento setup
psql:test/setup/TEST_INSTALL.sql:182: ERROR:  Error: Incorrect number of audit tables!
CONTEXT:  PL/pgSQL function inline_code_block line 16 at ASSERT
```

Fails because `spatial_ref_sys` table is automatically created in `pgmemento` schema when creating postgis extension.

Postgis also creates these views: 'geography_columns', 'geometry_columns', 'raster_columns', 'raster_overviews'
and a bunch of stored procedures.

ENV:
Clean Postgres 10 database
postgis-2.5

**Comment by raiviskrumins** [comment]
This happens only when user/schema == 'pgmemento' when invoking TEST.sql

**Comment by FxKu** [comment]
Thanks anyway for bringing it up :)
I could add a check in TEST.sql, that creates another schema if a `pgmemento` is already present.
