### ISSUE TITLE
fix testrun.sh

### ISSUE THREAD

**Issue by FxKu** [pgMemento/pgMemento#30]
TL;DR: test returns expected value but is not passed correctly to assertion

Final test in testrun.sh does not work properly during travis build (passing only locally).
Problem: The executed SQL file sets a temporary configuration parameter that only lives for one session. For some reason it is not known when running the DO block passed with the same psql command (with -1 set).

**Comment by dnsl48** [comment]
are you talking about this one?
```sql
DO $$ BEGIN
  ASSERT (SELECT current_setting('pgmemento.restore_value')) = 'two';
END; $$;
```

**Comment by dnsl48** [comment]
> Final test in testrun.sh does not work properly during travis build

Could you give a link to the broken build?

**Comment by FxKu** [comment]
https://travis-ci.org/pgMemento/pgMemento/jobs/515393212#L3346

I tried to store the result of the restore query in a transaction variable, to use it in the assertion. But seems that it runs in to different sessions, so that my setting is not visible. Maybe you have a better idea.

**Comment by dnsl48** [comment]
Yeah, I'm getting the same error locally. It's not just on travis.
I think that's because `psql -f` flag forces session exit at the end of file execution. It's described as
```
  -f, --file=FILENAME      execute commands from file, then exit 
```

I've been able to work it around like that (on my local):
```bash
read -r -d '\0' TEST_RESTORE <<'EOF'
  DO $$ BEGIN
    ASSERT (SELECT current_setting('pgmemento.restore_value')) = 'two';
  END; $$;\0
EOF

echo "$(cat /tmp/restore_data.sql); $TEST_RESTORE" | psql pgmemento_restore postgres -1
```

**Comment by FxKu** [comment]
That's it, thank you :)
