### ISSUE TITLE
Prevent users from editing log tables directly

### ISSUE THREAD

**Issue by nextstopsun** [pgMemento/pgMemento#35]
I'd like to prevent certain users from editing log tables. 
This should be possible with revoking editing permissions for log tables from a user and setting  trigger functions to run as `SECURITY DEFINER` so log tables cannot be edited directly.
Is it reasonable to set trigger functions to `SECURITY DEFINER` by default?

**Comment by FxKu** [comment]
With log tables you are referring to tables in the `pgmemento` schema, or tables you are auditing? I think anyone with write permissions to audited tables shall also be able to trigger changes to the audit trail. This would not be possible with `SECURITY DEFINER`, wouldn't it?

**Comment by nextstopsun** [comment]
By log tables I mean `pgmemento` ones. 
Of course a role with write permissions on audited table should be able to execute trigger function. 
But this role could be not granted write permissions to eg. `row_log` table directly. In this case a trigger function should have a `SECURITY DEFINER` option.
