### ISSUE TITLE
Possible issue with restore_recordset

### ISSUE THREAD

**Issue by stev-0** [pgMemento/pgMemento#36]
I am a little confused - when I run this query I get the correct state of the data before transaction 32 - i.e. grade:1 and login_count:3
  
`SELECT * FROM
  pgmemento.restore_record(1,32,'user','public', 1048, TRUE)
  AS (log JSONB);`

However, when I run this query:

`SELECT * FROM 
  pgmemento.restore_recordset(1,32,'user','public',TRUE)
  AS (log JSONB);`

I don't get any rows. I would have thought that restore_recordset was a superset of restore_record, or have I misunderstood?

**row_log:**
`1247	32	1048	"{"grade": 1, "login_count": 3}"`

**Comment by stev-0** [comment]
It looks like the issue might have been that my table was called `user` which isn't the best name, and I think there was a quoting issue

**Comment by FxKu** [comment]
Thanks for reporting. Glad you found a way to work around it. Still, sounds like something I could check, if I find time.
