### ISSUE TITLE
Table Partitioning

### ISSUE THREAD

**Issue by stephaneDunand** [pgMemento/pgMemento#37]
it would be nice that in a future version if it is possible to use table partitioning (https://www.postgresql.org/docs/11/ddl-partitioning.html).
what do you think about replicating stmt_date in the table_event_log and row_log tables ?

**Comment by FxKu** [comment]
Yeah, it's probably a good idea to have the temporal information everywhere, to partition e.g. row_log by time. You can give it a try and submit a PR :)

**Comment by FxKu** [comment]
The `table_event_log` and `row_log` now both have an `event_key` column consisting of the epoch timestamp, internal txid, table operator and table name (+ schema). This key now acts as reference between the two tables (but there is no foreign key constraint in place) and can also be used for partitioning.
