### ISSUE TITLE
new event_key in table log has redundant data

### ISSUE THREAD

**Issue by nextstopsun** [pgMemento/pgMemento#42]
In line 

https://github.com/pgMemento/pgMemento/blob/9baeba2e7e719b24a9b467bb0ee3b27fe39b40c5/ctl/UPGRADE.sql#L53

value 
```
extract(epoch from t.txid_time)
```
is repeated twice. This is unnecessary and doesn't add any uniqueness to key values. 
So when you have two events of the same type in one transaction this value won't be unique.

I guess what really was meant here is
```
extract(epoch from e.stmt_time)
```

So the whole key looks like:
```
event_key = concat_ws(';', extract(epoch from t.txid_time), extract(epoch from e.stmt_time), t.txid, e.op_id) 
```

@FxKu Is that true?

**Comment by FxKu** [comment]
in other places this value must come from `stmt_time`, that's true. But here, it's fine as I did not store the `statement_timestamp()` before. So, I simply set it equal to the transaction timestamp. Interestingly, even with new logged data these two timestamps will be identical in most cases.
