### ISSUE TITLE
Error when uninstalling pgMemento

### ISSUE THREAD

**Issue by matzello** [pgMemento/pgMemento#48]
When uninstalling pgMemento from my PostgreSQL 10 database, using the UNINSTALL_PGMEMENTO.sql script, I get the following error message:

C:\Program   Files\PostgreSQL\10\bin\pgMemento>"C:\Program Files\PostgreSQL\10\bin
--
\psql.exe" -h localhost -d ccdr -p   5432 -U pgadmin-mschn79534 -f "UNINSTALL_PGMEMENTO.sql"
Password for user pgadmin-mschn79534:
SET
 
Removing event triggers ...
drop_schema_event_trigger
---------------------------
 
 
 
Removing audit_id columns from audited   tables ...
psql:UNINSTALL_PGMEMENTO.sql:40:   ERROR:  relation   "slp20110006.d20180328_sa_birt
hs_pslk_source" does not exist
CONTEXT:    SQL statement "SELECT EXISTS (
SELECT
1
FROM
pg_attribute
WHERE
attrelid = ($2 \|\| '.' \|\| $1)::regclass::oid
AND attname = 'audit_id'
AND attislocal = 't'
AND NOT attisdropped
)"
PL/pgSQL function   drop_table_audit_id(text,text) line 4 at IF
SQL statement "SELECT   pgmemento.drop_table_audit_id($1, $2)"
PL/pgSQL function   drop_table_audit(text,text) line 4 at PERFORM

I have checked table pgmemento.audit_table_log and found an entry for table slp20110006.d20180328_sa_births_pslk_source with txid_range [1248,].  However, there is indeed no table d20180328_sa_births_pslk_source in schema slp20110006. This is a table name that previously existed but that has now been renamed.

Should the uninstall script cater for this eventuality of tables being deleted or renamed?

Is there any other way to safely uninstall/remove pgMemento from my PostgreSQL database?

Thanks in advance for any help.

**Comment by FxKu** [comment]
Thanks @matzello for raising this issue. I've also noticed that one cannot use the `audit_table_log` but should use the `audit_tables` view to remove pgMemento. Because the view only lists existing tables with the `audit_id` column. I'm currently working on a bigger PR, but could strip out this small fix for `UNINSTALL_PGMEMENTO` which contains this query:

```
SELECT
  pgmemento.drop_table_audit(
    table_name,
    schema_name,
    FALSE
  )
FROM
  pgmemento.audit_tables;
```

**Comment by matzello** [comment]
many thanks @FxKu !
I have used the following sightly amended version of your code snippet to update UNINSTALL_PGMEMENTO.sql, which seems to work to remove pgMemento from my PostgreSQL database:

SELECT
  pgmemento.drop_table_audit(
    tablename,
    schemaname
  )
FROM
  pgmemento.audit_tables;

**Comment by FxKu** [comment]
Yes without the underscore. I forgot that.
