### ISSUE TITLE
How do you track JSONB columns changes?

### ISSUE THREAD

**Issue by syabro** [pgMemento/pgMemento#5]
We store our main data inside one JSONB field. Can it track only what was changed inside jsonb?

**Comment by FxKu** [comment]
Hey there,
that's an interesting question. So the essential part you are looking for takes place in the pgmemento.log_update() trigger function in SETUP.sql file. I have to check, how it treats JSONB data when its part of the recorde data (OLD).
Will get back to you, soon.

**Comment by FxKu** [comment]
Ok, so I've did a simple test and I can say that if you change parts of a JSONB object, the whole old version of the JSON document will be logged.

```sql
CREATE TABLE json_tab (id INTEGER, j JSONB);
INSERT INTO json_tab VALUES (1, '{"a":1, "b":2}');
UPDATE json_tab SET j = jsonb_concat(j, '{"b":3}');
```

This example will produce the log `{"j": {"a": 1, "b": 2}}`.

**Comment by syabro** [comment]
@FxKu thanks :)
