### ISSUE TITLE
tables and columns including quotes in their names

### ISSUE THREAD

**Issue by mejiafabiandj** [pgMemento/pgMemento#6]
when creating a table like this

```
CREATE TABLE public."My-table"
(
  "My id" character varying(15),
...
)
```

triggers serveral errors:

..INIT.sql:36: ERROR:  relation «public.my-table» does not exist

**Comment by FxKu** [comment]
Problem is not the quotes for the column name, but for the table. I could rework all dynamic SQL code, so that quotes are replaced from schema and table identifiers, e.g.

```sql
EXECUTE format(
    'CREATE TRIGGER log_transaction_trigger
       BEFORE INSERT OR UPDATE OR DELETE OR TRUNCATE ON %I.%I
       FOR EACH STATEMENT EXECUTE PROCEDURE pgmemento.log_transaction()',
       replace($2,'"',''), replace($1,'"',''));
```

But, you could also try to not use any quotes in table names, as recommended [here](http://blog.lerner.co.il/quoting-postgresql/) 

;)

**Comment by FxKu** [comment]
wontfix + 1 month + no more feedback = closing issue

**Comment by FxKu** [comment]
A new issue regarding double quotes for table names popped up #13. I tried to add replace functions to the code and so far, it looks promising that this issue here is resolved as well. Still, I need to test restoring of such tables. So sorry, it kept so long for me to take a look again.

**Comment by FxKu** [comment]
Merged the PR. Now, quoted schemas, tables and columns can be audited. They can even contain doubles quotes within their name. The surrounding quotes are removed when stored in the log tables (like in Postgres system tables). What made this fix quite complicated was to check when to quote the idents and when it wasn't necessary.
