### ISSUE TITLE
ERROR: extension "pgmemento" has no installation script nor update path for version "0.7"

### ISSUE THREAD

**Issue by Zireael** [pgMemento/pgMemento#61]
Hi, I installed `pgmemento` (pre-compiled) in dockerfile image `bitnami/postgres:12.2` like so:

```
FROM bitnami/postgresql:12
USER root

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install unzip wget make

RUN wget https://github.com/pgMemento/pgMemento/releases/download/v0.7/pgmemento-0.7.zip

RUN unzip pgmemento-0.7.zip

RUN cd pgmemento-0.7 \ 
  && make install PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config

COPY ./init/ /docker-entrypoint-initdb.d/
USER 1001
```

When trying to install the extension, I'm getting error
`SQL Error [22023]: ERROR: extension "pgmemento" has no installation script nor update path for version "0.7"`

input:
```
SELECT * FROM pg_available_extensions WHERE name = 'pgmemento';
CREATE EXTENSION pgmemento;
```
output:
```
"name","default_version","installed_version","comment"
pgmemento,"0.7",,Audit trail with schema versioning for PostgreSQL using transaction-based logging
```

```
SQL Error [22023]: ERROR: extension "pgmemento" has no installation script nor update path for version "0.7"

```

**Comment by Zireael** [comment]
Got it to work...
What I did was to just execute *.sql scripts from [source](https://github.com/pgMemento/pgMemento/tree/master/src) and initialize extension on a schema with `SELECT pgmemento.init('public');`
This is much easier way than playing around with `make && sudo make install`. I'd suggest you add a note that this can be installed by just running *.sql scripts on the database. 
It would be beneficial if the files were numbered in order to be executed, ie `01-SCHEMA.sql`, `02-SETUP.sql` and so on.

**Comment by dnsl48** [comment]
> RUN cd pgmemento-0.7 \ 
  && make install PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config

Perhaps that should have been `make && make install`, and not `make install` straight away.

**Comment by dnsl48** [comment]
> This is much easier way than playing around with make && sudo make install

Fair enough. However, `make && make install` is the way recommended by PostgreSQL devs (and pgxn) of installing extensions. It is more standardized than doing it manually. Also, it takes care for setting up correct permissions and extension upgrades to the newer versions in the future. Doing that all manually is just not the optimal way IMHO.

**Comment by Zireael** [comment]
> > RUN cd pgmemento-0.7 \
> > && make install PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config
> 
> Perhaps that should have been `make && make install`, and not `make install` straight away.

I had some problems with Docker environment refusing to build initially (base image striped of make, build-essential and running rootless), complaining about lack of ./configure and so on. After I tried adding manual path to PG_CONFIG it went ahead, so I didn't go back to uncomment some parts of the command chain.

Just tried with make added and the Docker build seemed to go ahead, and `CREATE EXTENSION pgmemento;` seems to be responsive in the database now.
```
RUN cd pgmemento-0.7 \ 
  && make \ 
  && make install PG_CONFIG=/opt/bitnami/postgresql/bin/pg_config
```

NB: You have changed some function parameter names compared to what's written in the wiki (I fixed schema_name -> schemaname) and there doesn't seem to be a function named get_audit_information expected by this extension I was trying to use: https://github.com/mayflower/postgraphile-audit-plugin/issues/2#issuecomment-630459647

I'd prefer to use `make && make install` too, but hey, sometimes you take what you get to work.

**Comment by FxKu** [comment]
@Zireael we have a sql [script](https://github.com/pgMemento/pgMemento/blob/master/INSTALL_PGMEMENTO.sql) that installs everything instead of using the extension. This has been the way to go for years before we had the extension :smiley:

Maybe, I should still mention it in the README, so that nobody has to fiddle with the order.

**Comment by Zireael** [comment]
> Can you point me to the part in the wiki that is not in sync with the code. Yeah, I had to change some fields because of new columns in the log tables.

I fixed `schema_name` to `schemaname` in https://github.com/pgMemento/pgMemento/wiki/Initialize-auditing
From a quick look, the rest of examples seem fine.

**Comment by FxKu** [comment]
I think this one we can close by now. README and docs have been updated.
