### ISSUE TITLE
create_table_audit function throws an error

### ISSUE THREAD

**Issue by nextstopsun** [pgMemento/pgMemento#62]
`pgmemento.create_table_audit` function throws an error.
It's easy to replicate:

```
CREATE DATABASE test;
--switch to database test;

CREATE EXTENSION pgmemento;

CREATE TABLE test_tab (
  id INTEGER
);

SELECT pgmemento.create_table_audit(
         tablename := 'test_tab',
         schemaname := 'public',
         audit_id_column_name := 'audit_id');
```

You'll get:
```
[42701] ERROR: column "audit_id" of relation "test_tab" already exists Where: SQL statement "ALTER TABLE public.test_tab ADD COLUMN audit_id BIGINT DEFAULT nextval('pgmemento.audit_id_seq'::regclass) UNIQUE NOT NULL" PL/pgSQL function pgmemento.create_table_audit_id(text,text,text) line 8 at EXECUTE SQL statement "SELECT pgmemento.create_table_audit_id($1, $2, $3)" PL/pgSQL function pgmemento.create_table_audit(text,text,text,boolean,boolean,boolean) line 41 at PERFORM
```

I guess `create_table_audit_id` function is called twice here:
First `create_table_audit` finds nothing in `audit_schema_log` table and calls [create_schema_audit](https://github.com/pgMemento/pgMemento/blob/master/src/SETUP.sql#L1306)

Which in turn calls [create_table_audit](https://github.com/pgMemento/pgMemento/blob/master/src/SETUP.sql#L1363) for this particular table. This one creates an id column, so the outer call fails.

My guess is there should be an `ELSE` block [here](https://github.com/pgMemento/pgMemento/blob/master/src/SETUP.sql#L1307), so standalone `create_table_audit_id` is called only when schema audit is already set.

**Comment by FxKu** [comment]
You're right, the whole rest of the function actually should be in an else block as everything has already been passed in the inner call. Will fix.

**Comment by nextstopsun** [comment]
As a side thought, should `create_schema_audit` really be called here?

**Comment by FxKu** [comment]
Well, I could also return an error, if the schema is not registered for auditing, yet. I thought, it would be more convenient if pgMemento does it for you.
