### ISSUE TITLE
Summary of currently monitored schemas

### ISSUE THREAD

**Issue by matzello** [pgMemento/pgMemento#7]
Would you be able to tell me how I can find out which of the schemas of my database are monitored at any one time? I have multiple schemas in my databases and have started and stopped auditing for some of the them multiple times (using the stop_auditing.sql and start_auditing.sql scripts) and lost track of it. Is there a way to find out which ones are currently monitored?

**Comment by FxKu** [comment]
Have you already checked the `audit_tables` view inside the `pgmemento` schema? In this view I list which tables (in which schemas) are currently audited. There are two columns to define the min and max transaction ID associated with the table. `tg_is_active` tells you if the pgMemento trigger exists and if it's enabled or not. Does this help?

**Comment by matzello** [comment]
@FxKu: Thanks, that's exactly what I was after. I have now noticed that it was described in the installation details under 5.1. My apologies, I should have read the description more closely. Thanks for pointing it out!

**Comment by FxKu** [comment]
Great to hear that :) Please, let me know in case you find something else that might be missing in pgMemento.
