### ISSUE TITLE
Full record history between two dates

### ISSUE THREAD

**Issue by jorge-pascual** [pgMemento/pgMemento#74]
Hi all!

First of all.. congrats for this amazing script!. I just love it!

I have a newbie question (sorry)... I would like to have a "full history" of a record (or even better, a range of records). So, given an audit_id (or a set of them) and a "from date" and "to date", I would like to see the serie of records ordered by date where each record has the full state (all fields with its data) at a given date. 

date | audit_id|field 1 | field 2 | ... | field n
-----|------|-------|-------|----|--------
2020/09/18 | 1 | original value 1 | original value 2 | ...  |original value n |  
2020/09/20 | 1 | original value 1 | __updated value 2__ | ... |original value n |  
2020/09/25 | 1 | __updated value 1__ | updated value 2 | ... |__updated value n__ | 

This is kind of what you can do with temporal_tables. 

Is there any "easy" way to reach that?. 

I've seen that if I call 

```sql
SELECT
  *
FROM
  pgmemento.restore_record(1, 9, 'company_limits_assets', 'platform', 1, TRUE)
  AS (log jsonb);
```

I get the final status... so I have to query the transaction table, get all transactions between two dates and call `pgmemento.restore_record` one time per transaction... however, I think that this is far from being efficient. 

Is there any other way?

Thank you!

-- Jorge

**Comment by FxKu** [comment]
Hi and thanks. It seems what you are looking for is described on [this](https://github.com/pgMemento/pgMemento/wiki/Restore-multiple-versions-at-once) wiki page. The `restore_records` function is meant for that.

**Comment by jorge-pascual** [comment]
Just amazing!. It was what I was looking for. Thank you @FxKu, what a great job!.
