### ISSUE TITLE
Installation instructions are broken, what to "make"?

### ISSUE THREAD

**Issue by kannes** [pgMemento/pgMemento#75]
https://github.com/pgMemento/pgMemento#quickstart says 

> To use pgMemento as an extension download and unzip the
> pgmemento-<release-version>.zip archive, change to extracted folder and
> run the following commands from within a shell environment:
> 
> ```bash
> make
> sudo make install
> ```

However there is no Makefile in the root of the archive, not in `src`. There is one in `extension/pgxn` but trying to use that results in an error:

```
~/pgMemento-0.7.1/extension/pgxn# make
grep: pgmemento.control: No such file or directory
grep: pgmemento.control: No such file or directory
make: *** No rule to make target 'sql/pgmemento.sql', needed by 'sql/pgmemento--.sql'.  Stop.
```
It's probably not the Makefile the README was referencing though anyways.

Installation worked perfectly fine for me using the described "classic way" but I wanted to let you know. :)

**Comment by FxKu** [comment]
Ah, the quickstart is referring to the already build extension zip for [PGXN](https://pgxn.org/dist/pgmemento/). You have just used the zipped source code, because I forgot to add the build zip to the release. Done now.

**Comment by kannes** [comment]
That makes sense, thanks!
