### ISSUE TITLE
Logging application user information?

### ISSUE THREAD

**Issue by dnd** [pgMemento/pgMemento#8]
Maybe pgMememto can already do this, and I just didn't see it, but is there a way to specify on the client side what user is making the changes? My applications by and large all connect as the same PG user in a pool, and every query runs from that pool. So every change through the app would just log the user_name as `myapp` or whatever, which isn't super useful. 

I could implement an `updated_by` or `updated_by_id` field on each audited table, and that would have the user that made the change in the audit log, but it's not at the top level with the connection username where it would be more convenient to access. Also, does pgMemento store a diff of the changes? If so, then if the same user updated a row multiple times, that `updated_by` field wouldn't be present in the diff, and make it difficult to track.

I'm also thinking about things such as logging maybe the ip address of the application user which has similar problems.

Is there any way for pgMemento to lift this information up to the `transaction_log` table? Maybe PG has some kind of connection context/session that could be used to set this information that pgMemento could then read in? Even if it just dumped this information into a JSONB field like `transaction_log.client_session` or something could be really useful.

**Comment by FxKu** [comment]
Hey there. 
You got it right. pgMemento does not store more information other than `user_name` and `client_name`. And `updated_by` would not appear in the logs, if the value does not change.

I'm open for extending the `transaction_log` table to store more information about the user session. IP address sounds reasonable. Maybe you and I could play around with some [system functions](https://www.postgresql.org/docs/9.5/static/functions-info.html) to see if we can get the result we want?

**Comment by dnd** [comment]
I haven't had a chance to play around with the system functions at all yet, but if there's a way to access some kind of generic session information to store I think that would be best. For example, while end user IP might be a good top level field that applies to most, something like `request_id` probably doesn't, but is something I would like to log if possible.

Maybe there could be some additional first class values that have dedicated columns, and then others just get dumped into a JSONB column? Maybe the trigger that does the logging could accept some type of configuration or arguments to tell it what data to keep if there's a way to get general session/variable information?

**Comment by FxKu** [comment]
I tried some system functions but the only one that looked relevant for your use case is `pg_backend_pid()`, which returns an identifier for the connection. I also found [this](https://stackoverflow.com/questions/5070903/identifying-a-connection-id-in-postgres) question, which sounds pretty similar to your problem. I'll do some more research in this direction.

I still think such information is best suited for the `transaction_log` and non the `row_log` table. Generally, it's possible to change the triggers, that some columns are logged seperatly from the JSONB audits, e.g. the `audit_id` column I use for each table.

**Comment by dnd** [comment]
Sorry if I worded that poorly. I definitely agree that the session information would belong on the `transaction_log` table. I was just saying that in my example `request_id` is not really a field that everyone would necessarily need, so having that be a first class field probably doesn't make sense. I was thinking of a `transaction_log` structure like:

```
transaction_log (
  ...
  app_user_name text
  app_user_ip inet
  client_session jsonb
)
```

 In the link you posted the comment by davea looks interesting by using `current_setting`, and the app using `set_config`. A quick test shows that prefixing with local does indeed work. 

Then maybe `INIT.sql` could prompt the user for session data they want to capture, like a comma separated list or something? That data could then be packed into the `client_session` field as jsonb. 

What do you think of that?

**Comment by FxKu** [comment]
I had a similar idea regarding the `set_config` command ;)
I could create an extra field in the `transaction_log` table which is fed with the value of `current_setting('pgmemento.sessioninfo')` everytime the trigger is fired. So it's up to the user to put something inside this variable. Otherwise it's NULL.

So far, I see no way to retrieve the IP of the user's machine. In your case the result for `inet_client_addr()` would always be the address from the connection pool, wouldn't it? I read that one could write a function in something like PL/perl to resolve such information. Hm, I think I would leave this to the user and just provide one more field to put any sorts of session parameters.

**Comment by dnd** [comment]
So the developer would be responsible for maintaining jsonb in that specific config setting? I think that's good. 

For retrieving the end user IP I was only thinking that would be possible if for example there was a specific field  `pgmemento.end_user_ip` that would be checked for that value to turn it into a first class field. I think with the proposed solution of just dumping a whole `sessioninfo` setting into the table that that should be fine, and the user can define whatever structure they want. I also agree that there's no need to go into complicated functions.

**Comment by FxKu** [comment]
I would put plain text in this session variable - not JSONB. I'll have some time this weekend to make the changes we talked about. Thanks again for describing your use case and for your interest in pgMemento.

**Comment by dnd** [comment]
Wouldn't it be better to store the data as json though so it could be queried better by the user? If multiple values were stored in there the only way to get at specific data would be to pull all the records,and go through each one. For example, checking the log trail to see everything the was changed by a given application user yesterday, or from an example I gave above, what records were changed by a specific request_ID.

**Comment by francoricci** [comment]
I make a little enhancement to pgmemto: log the application_name postgresql parameter.
During connection, it's possible to specify application_name parameter. It's can bu useful to store information abut application user that generally is different from connection username.
Now in pgmemento.transaction_log table there is a column called application_name.
I also added a view pgmemento.audit_full to get a complete list of changes.

Franco
[SETUP.sql.txt](https://github.com/pgMemento/pgMemento/files/2319076/SETUP.sql.txt)

**Comment by FxKu** [comment]
I've merged the dev branch, finally. Now, you can set the configuration paramter `pgmemento.session_info` for a db connection or transaction and it will be logged in the `transaction_log` table as JSONB. Note that the value of session_info needs to be valid JSON. Otherwise you cannot use the JSONB operators for querying.

You will see, that I've also changed a couple of other things. You can run the `UPGRADE_v05_to_v06.sql` script to lift an existing pgmemento log up to the newest version.

**Comment by francoricci** [comment]
Thanks

Franco

**Comment by Gavin777** [comment]
Hi, thanks for making this improvement! My friend and I were just thinking about doing something like this to fit our needs. 

I was trying this out but the session_info column wasn't being populated as expected. I set up pgMemento as specified on the README and the schema looks correct. Here's the basic flow that I tried, please let me know if I missed a step:

1. Connect on psql 
2. Call the set_config function similar to the example in the README
3. Make sure "SHOW pgmemento.session_info" returns the JSONB in step 2
4. Make an update on any table that has triggers 
5. "SELECT * FROM pgmemento.transaction_log WHERE session_info <> NULL;" but this returns 0 rows
