### ISSUE TITLE
Changing a column multiple times in one transaction breaks restoring

### ISSUE THREAD

**Issue by bakkerthehacker** [pgMemento/pgMemento#81]
If a column has been changed multiple times in one transaction, multiple entries are added into `audit_column_log`.  All but one of these entries will have an empty `txid_range`.  This kinda makes sense, there isn't a transaction that would match those intermediate columns, so the range is empty.  

However, when these empty range entries are present, the restore functionality no longer works for these tables.  All of the restore functions end up using `pgmemento.restore_query()` and that function return duplicate statements for the columns that were changed multiple times in one transaction earlier.  `pgmemento.get_column_list()` does not duplicate the columns, so i'm thinking is something to do with the way `pgmemento.restore_query()` deals with ranges that is incompatible with empty ranges.

**Comment by FxKu** [comment]
I have indeed found code parts that did not care for these empty ranges. #86 should fix it. Thanks for raising.
