### ISSUE TITLE
Renaming multiple times in one transaction is not recorded by auditing system

### ISSUE THREAD

**Issue by bakkerthehacker** [pgMemento/pgMemento#82]
When changing a table name, column name or type name, nothing is changed in either `audit_table_log` or `audit_column_log`.  This prevents properly restoring data on the renamed table.  

I have tried the following types of queries and not seen the updates to audit tables as I would expect:

`ALTER TABLE old_table RENAME TO new_table;`
`ALTER TYPE old_enum RENAME TO new_enum;`
`ALTER TABLE table RENAME COLUMN old_column TO new_column;`

Not sure if there are more queries that are being missed.

**Comment by bakkerthehacker** [comment]
I would indeed expect these old tables/columns to get upper txid boundaries when renamed, but this currently does not happen.

Interesting to find out that type renaming is not supported.  Not a big deal but would be nice to know ahead of time, maybe in docs somewhere.  Would be very nice to have it working.

**Comment by FxKu** [comment]
I mean, it's even tested that this [works](https://github.com/pgMemento/pgMemento/blob/747aa78369e93453dd2444d39b6381901a60118e/test/ddl_log/TEST_ALTER_COLUMN.sql#L141). Not sure what's up with your event triggers. One can add debug messages to `table_alter_pre_trigger` to find out what happens internally. Is the event is logged in `table_event_log`?

**Comment by bakkerthehacker** [comment]
After a bit of investigation, it seems this issue is similar to https://github.com/pgMemento/pgMemento/issues/81.  I was running multiple renames in one transaction and only the first `RENAME TABLE` shows up in the `table_event_log`.

**Comment by FxKu** [comment]
I tried to replicate this by renaming a table, change column data type and renaming column all in one transaction but events and data were logged as expected. Haven't tested changing the type of a column in one transaction, too. But, I found some issue related to empty txid_ranges.

**Comment by FxKu** [comment]
Closing this issue now. Empty txid_ranges are already reflected in restore and revert queries since 0.7.2. Feel free to reopen for further question.
