### ISSUE TITLE
0.7.2 update error

### ISSUE THREAD

**Issue by antoniusz** [pgMemento/pgMemento#88]
Hi, 
I've got this error message:

ERROR:  extension "pgmemento" has no update path from version "0.7.1" to version "0.7.2"
SQL state: 22023

**Comment by FxKu** [comment]
hm, did not know I have to add a script between each version. Could you try with the zip file I've attached to the release?
https://github.com/pgMemento/pgMemento/releases/tag/v0.7.2

**Comment by antoniusz** [comment]
ALTER EXTENSION pgmemento UPDATE TO '0.7.2';
ALTER EXTENSION
Query returned successfully in 3 secs 261 msec.  :+1:

**Comment by antoniusz** [comment]
There is no pgmemento--0.7.2.sql file in postgreql's extension directory.

rw-r--r-- 1 root root  12678 2020 okt   24 pgmemento--0.7--0.7.1.sql
-rw-r--r-- 1 root root  30691 máj    4 20.44 pgmemento--0.7--0.7.2.sql
-rw-r--r-- 1 root root  30691 máj    4 20.44 pgmemento--0.7.1--0.7.2.sql
-rw-r--r-- 1 root root 204242 2020 okt   24 pgmemento--0.7.1.sql
-rw-r--r-- 1 root root    239 máj    4 20.44 pgmemento.control
