### ISSUE TITLE
Adding columns to a wide table breaks tracking

### ISSUE THREAD

**Issue by ekeuus** [pgMemento/pgMemento#97]
Hi all,

When we add new columns to a wide(ish) table that is tracked, we get the following issue which makes the migration fail.

```
2022-08-23 08:57:26.084 UTC [34] ERROR:  cannot pass more than 100 arguments to a function at character 104
2022-08-23 08:57:26.084 UTC [34] QUERY:  INSERT INTO pgmemento.row_log AS r (audit_id, event_key, new_data)
SELECT audit_trail_id, $1, jsonb_build_object('col', "col", 'col2', col2, ...) AS content
```

The statement itself is
`2022-08-23 08:57:26.084 UTC [34] STATEMENT:  ALTER TABLE "public"."table" ADD COLUMN "column" TIMESTAMP WITH TIME ZONE DEFAULT NULL;`

Please let us know how to proceed with this as we might have to disable tracking in PROD due to this issue if we want to release these new columns.

**Comment by FxKu** [comment]
I did not know about this limit of `jsonb_build_object` function. Checking mailing list I found that one can also use `jsonb_object` function with an array. Should be relatively easy to fix. I will see, if I find time on the weekend or you give it a shot.

**Comment by ekeuus** [comment]
Any update on this? I could take a look at the code myself if you don't have enough time.

**Comment by ekeuus** [comment]
Seems like we need to just change the logic https://github.com/pgMemento/pgMemento/blob/4a2029684307450811e366de31a074277dc8a810/src/SETUP.sql#L864 and https://github.com/pgMemento/pgMemento/blob/4a2029684307450811e366de31a074277dc8a810/src/SETUP.sql#L898 to use jsonb_object instead.

`SELECT %I, $1, jsonb_build_object('||pgmemento.column_array_to_column_list($1)||') AS content`
TO
`SELECT %I, $1, json_object(LIST_OF_COLUMNS, LIST_OF_VALUES) AS content`.

**Comment by ekeuus** [comment]
I was playing around a bit, and it seems like `jsonb_object(keys text[], values text[])` won't work as it only accepts arrays of text. Meaning that variable values that exist in both arrays can only be of type text.

Works:
`select * from jsonb_object(array['a', 'b'], array['true', 'false'])`

Does not work:
`select * from jsonb_object(array['a', 'b'], array[true, false])`

I will try to implement a way to call `jsonb_build_object` with <= 100 arguments in batches somehow to try to fix it in that way.

**Comment by ekeuus** [comment]
@FxKu I opened up a PR here https://github.com/pgMemento/pgMemento/pull/99

**Comment by FxKu** [comment]
Great @ekeuus you gave it a try. Let me have a look the next days. Sorry for being silent. A lot of stuff happened in my private life taking all my attention.

I will take care of any UPGRADE scripts. You don't have to think about it for your PR.

**Comment by ekeuus** [comment]
No worries at all! Just do it whenever. No pressure.

Worst case, we can just roll with this unofficial version until there is a solution on pgmemento side. :)
